import '../styles/globals.css'

export const metadata = {
  title: "Form",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="html-container"
    >
      <body>{children}</body>
    </html>
  );
}
