export const metadata = {
  title: "Form",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      style={{
        background: "linear-gradient(45deg, #FE6B8B 30%, #FF8E53 90%)",
        height: "100%",
        width: "100%",
      }}
    >
      <body>{children}</body>
    </html>
  );
}
